# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/refs/heads/main/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

python:
  install:
    - method: uv
      command: pip
      requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
