# .readthedocs.yaml - https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  version: '3.8'
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
