# .readthedocs.yaml - https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: mambaforge-latest

conda:
  environment: docs/rtd_environment.yaml

formats:
  - htmlzip
  - pdf
