name: build

on:
  workflow_call:
    outputs:
      date:
        value: ${{ jobs.variables.outputs.date }}
      runs-on:
        value: ${{ jobs.variables.outputs.runs-on }}
      python-version:
        value: ${{ jobs.variables.outputs.python-version }}
  workflow_dispatch:
  push:
  release:
    types:
      - published

concurrency:
  group: build-${{ github.ref }}

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - id: runs-on
        run: echo 'runs-on=["ubuntu-latest", "macos-latest"]' >> $GITHUB_OUTPUT
      - id: python-version
        run: echo 'python-version=["3.12", "3.13", "3.14"]' >> $GITHUB_OUTPUT
      - id: date
        run: echo "date=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT
    outputs:
      date: ${{ steps.date.outputs.date }}
      runs-on: ${{ steps.runs-on.outputs.runs-on }}
      python-version: ${{ steps.python-version.outputs.python-version }}
  build:
    needs: [ variables ]
    strategy:
      fail-fast: false
      matrix:
        runs-on: ${{ fromJSON(needs.variables.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.variables.outputs.python-version) }}
    runs-on: ${{ matrix.runs-on }}
    name: build (Python ${{ matrix.python-version }}, ${{ matrix.runs-on }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
            ${{ (matrix.python-version == '3.12' || matrix.python-version == '3.13') && 'numpy' || '' }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.variables.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "filename=stenv-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.date }}.yaml" >> $GITHUB_OUTPUT
        id: output
      - run: |
          micromamba env export --no-build | grep -v "name:" | grep -v "prefix:" > ${{ steps.output.outputs.filename }}
          cat ${{ steps.output.outputs.filename }}
      - run: uv pip install pytest
      - run: pytest tests/test_import.py
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: ${{ steps.output.outputs.filename }}
          path: ${{ steps.output.outputs.filename }}
          archive: false
      - if: (github.event_name == 'release' && github.event.action == 'published')
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de  # 2.11.5
        with:
          file: ${{ steps.output.outputs.filename }}
