name: tests

on:
  pull_request:
    paths:
      - .github/workflows/*
      - environment.yaml
      - tests/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  PYSYN_CDBS: https://ssb.stsci.edu/trds
  jref: https://ssb.stsci.edu/trds_open/jref
  lref: https://ssb.stsci.edu/cdbs/lref
  CRDS_PATH: /tmp/crds_cache
  CRDS_CLIENT_RETRY_COUNT: 3
  CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
  LD_LIBRARY_PATH: /usr/local/lib

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  crds-contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@main
  test_acstools:
    needs: [build]
    strategy:
      matrix:
        package: [acstools]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/acstools]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} --slow -n auto
  test_asdf:
    needs: [build]
    strategy:
      matrix:
        package: [asdf]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [asdf-format/asdf]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} "stdatamodels>=5" pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} --durations=10 -n auto
  test_calcos:
    needs: [build, crds-contexts]
    env:
      CRDS_OBSERVATORY: hst
      CRDS_SERVER_URL: https://hst-crds.stsci.edu
      CRDS_CONTEXT: ${{ needs.crds-contexts.outputs.hst }}
    strategy:
      matrix:
        package: [calcos]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/calcos]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ env.CRDS_OBSERVATORY }}-${{ env.CRDS_CONTEXT }}
          restore-keys: |
            crds-${{ env.CRDS_OBSERVATORY }}-
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: uv pip install .[test] pytest-xdist
        working-directory: ./${{ matrix.package }}/
      - run: calcos la8n01qkq_rawtag_a.fits
        working-directory: ./${{ matrix.package }}/
      - run: pytest --slow -n auto
        working-directory: ./${{ matrix.package }}/
  test_ccdproc:
    needs: [build]
    env:
      SETUP_XVFB: True
    strategy:
      matrix:
        package: [ccdproc]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [astropy/ccdproc]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} -W ignore -n auto
  test_costools:
    needs: [build]
    strategy:
      matrix:
        package: [costools]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/costools]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} -n auto
  crds_test_cache:
    needs: [build]
    uses: spacetelescope/crds/.github/workflows/cache.yml@main
  test_crds:
    needs: [build, crds_test_cache]
    env:
      CRDS_PATH: /tmp/crds-cache-default-test
      CRDS_TEST_ROOT: /tmp
      CRDS_TESTING_CACHE: /tmp/crds-cache-test
      CRDS_SERVER_URL: https://hst-crds.stsci.edu
      CRDS_MODE: local
    strategy:
      matrix:
        package: [crds]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/crds]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ${{ needs.crds_test_cache.outputs.path }}
            ${{ needs.crds_test_cache.outputs.testing_cache }}
          key: ${{ needs.crds_test_cache.outputs.key }}
          restore-keys: |
            test-cache-
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: micromamba install -y filelock requests
      - run: uv pip install parsely roman-datamodels git+https://github.com/spacetelescope/jwst
      - run: uv pip uninstall crds && ./install && uv pip install .[submission,test,docs,synphot]
        working-directory: ./${{ matrix.package }}/
      - run: ./runtests
        working-directory: ./${{ matrix.package }}/
  test_drizzlepac:
    needs: [build, crds-contexts]
    env:
      CRDS_OBSERVATORY: hst
      CRDS_SERVER_URL: https://hst-crds.stsci.edu
      CRDS_CONTEXT: ${{ needs.crds-contexts.outputs.hst }}
    strategy:
      matrix:
        package: [drizzlepac]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/drizzlepac]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ env.CRDS_OBSERVATORY }}-${{ env.CRDS_CONTEXT }}
          restore-keys: |
            crds-${{ env.CRDS_OBSERVATORY }}-
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: uv pip install -e .[test] pytest-xdist
        working-directory: ./${{ matrix.package }}/
      - run: pytest -n auto
        working-directory: ./${{ matrix.package }}/
  test_hstcal:
    needs: [build, crds-contexts]
    env:
      CRDS_OBSERVATORY: hst
      CRDS_SERVER_URL: https://hst-crds.stsci.edu
      CRDS_CONTEXT: ${{ needs.crds-contexts.outputs.hst }}
    strategy:
      matrix:
        package: [hstcal]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/hstcal]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ env.CRDS_OBSERVATORY }}-${{ env.CRDS_CONTEXT }}
          restore-keys: |
            crds-${{ env.CRDS_OBSERVATORY }}-
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: uv pip install pytest crds ci-watson pytest-xdist
      - run: pytest ./tests/ --slow -n auto
        working-directory: ./${{ matrix.package }}/
  test_jwst:
    needs: [build, crds-contexts]
    env:
      CRDS_OBSERVATORY: jwst
      CRDS_SERVER_URL: https://jwst-crds.stsci.edu
      CRDS_CONTEXT: ${{ needs.crds-contexts.outputs.jwst }}
    strategy:
      matrix:
        package: [jwst]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/jwst]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ env.CRDS_OBSERVATORY }}-${{ env.CRDS_CONTEXT }}
          restore-keys: |
            crds-${{ env.CRDS_OBSERVATORY }}-
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} -n auto
  test_reftools:
    needs: [build]
    strategy:
      matrix:
        package: [reftools]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/reftools]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} -n auto
  test_stistools:
    needs: [build]
    strategy:
      matrix:
        package: [stistools]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/stistools]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: uv pip install .[test] pytest-xdist
        working-directory: ./${{ matrix.package }}/
      - run: pytest -n auto
        working-directory: ./${{ matrix.package }}/
  test_stsynphot:
    needs: [build]
    env:
      PYSYN_CDBS: https://ssb.stsci.edu/trds
    strategy:
      matrix:
        package: [stsynphot]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/stsynphot_refactor]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./${{ matrix.package }}/
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
          fetch-depth: 0
      - run: uv pip install .[test] pytest-xdist
        working-directory: ./${{ matrix.package }}/
      - run: pytest --remote-data -n auto
        working-directory: ./${{ matrix.package }}/
  test_synphot:
    needs: [build]
    strategy:
      matrix:
        package: [synphot]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/synphot_refactor]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} --remote-data -n auto
  test_wfpc2tools:
    needs: [build]
    strategy:
      matrix:
        package: [wfpc2tools]
        runs-on: ${{ fromJSON(needs.build.outputs.runs-on) }}
        python-version: ${{ fromJSON(needs.build.outputs.python-version) }}
        repository: [spacetelescope/wfpc2tools]
    runs-on: ${{ matrix.runs-on }}
    name: ${{ matrix.package }} (${{ matrix.runs-on }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ./stenv/
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: ./stenv/environment.yaml
          condarc: |
            use_uv: true
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-environment-key: environment-${{ matrix.python-version }}-${{ needs.build.outputs.date }}
          init-shell: bash
          generate-run-shell: false
          post-cleanup: none
      - run: echo "version=$(uv pip list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
      - run: uv pip install ${{ matrix.package }}[test]==${{ steps.package_version.outputs.version }} pytest-xdist
      - run: pytest --pyargs ${{ matrix.package }} -n auto
